/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufu.facom.persim.view;

import br.ufu.facom.frameworkpim.control.EventoControl;
import br.ufu.facom.frameworkpim.control.StickyNotesControl;
import br.ufu.facom.frameworkpim.view.CadastroEventoIFrame;
import br.ufu.facom.frameworkpim.view.CadastroStickyNotesIFrame;
import br.ufu.facom.frameworkpim.view.CalendarIFrame;
import br.ufu.facom.frameworkpim.view.StickyNotesIFrame;
import br.ufu.facom.persim.config.Path;
import br.ufu.facom.persim.control.DatabaseConfigControl;
import br.ufu.facom.persim.control.EventoControlImpl;
import br.ufu.facom.persim.control.StickyNotesControlImpl;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Hugo
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        setMainWindowConfigurations();
        setDesktopConfigurations();
    }

    private void setMainWindowConfigurations() {
        this.initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(Path.getImagePath("persimlogo.png")));
        this.setTitle("PERSIM - Personal Student Info. Manager");
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(tela.width, tela.height);
        this.setVisible(true);

    }
    private void setDesktopConfigurations () {
//        StickyNote sn = new StickyNote("tetse sdfhjkasd", 200, 200);
        stickyNotesControl = new StickyNotesControlImpl();
//        StickyNotesIFrame snf = new StickyNotesIFrame(sn, stickyNotesControl);
        
        
        this.stickyNotes = stickyNotesControl.buildStickyNotesIFrames();
        for (Iterator<StickyNotesIFrame> it = stickyNotes.iterator(); it.hasNext();) {
            StickyNotesIFrame stickyNotesIFrame = it.next();
            this.desktopPane.add(stickyNotesIFrame);
        }
        
        eventoControl = new EventoControlImpl();
        CalendarIFrame cf = new CalendarIFrame(eventoControl);
        
        this.calframe = cf;
        this.desktopPane.add(this.calframe);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        periodoMenu = new javax.swing.JMenu();
        novoPeriodoMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        disciplinaMenu = new javax.swing.JMenuItem();
        criarMenu = new javax.swing.JMenu();
        eventoMenu = new javax.swing.JMenuItem();
        lembreteMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        periodoMenu.setText("Periodo");

        novoPeriodoMenuItem.setText("Novo Periodo");
        novoPeriodoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoPeriodoMenuItemActionPerformed(evt);
            }
        });
        periodoMenu.add(novoPeriodoMenuItem);

        jMenuItem1.setText("Estatísticas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        periodoMenu.add(jMenuItem1);

        disciplinaMenu.setText("Disciplina");
        disciplinaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disciplinaMenuActionPerformed(evt);
            }
        });
        periodoMenu.add(disciplinaMenu);

        menuBar.add(periodoMenu);

        criarMenu.setText("Criar");

        eventoMenu.setText("Evento");
        eventoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventoMenuActionPerformed(evt);
            }
        });
        criarMenu.add(eventoMenu);

        lembreteMenuItem.setText("Lembrete");
        lembreteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lembreteMenuItemActionPerformed(evt);
            }
        });
        criarMenu.add(lembreteMenuItem);

        menuBar.add(criarMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novoPeriodoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoPeriodoMenuItemActionPerformed
        int resp = JOptionPane.showConfirmDialog(this, "Deseja começar um novo período?"
                + " Você irá perder todos os dados deste período.", "Novo período",
                JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE);
        if (resp == 0) {
            DatabaseConfigControl.resetDB();
            this.desktopPane.removeAll();
            this.setDesktopConfigurations();
            this.desktopPane.repaint();
        }
    }//GEN-LAST:event_novoPeriodoMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(this, "Não implementado para versão gratuita!", "Ops!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void disciplinaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disciplinaMenuActionPerformed
        this.cadDisc = new CadastroDisciplina();
        this.desktopPane.add(this.cadDisc);
        this.cadDisc.setVisible(true);
    }//GEN-LAST:event_disciplinaMenuActionPerformed

    private void eventoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventoMenuActionPerformed
        this.eventFrame = new CadastroEventoIFrame(eventoControl);//instancia a classe iFrmCliente
        desktopPane.add(this.eventFrame);//adiciona o cliente no seu JdesktopPane
        this.eventFrame.setLocation(400, 0);//colocar a tela iFrmCliente na posiÃ§Ã£o(0,0)
        this.eventFrame.setVisible(true);//deixa visÃ­vel
    }//GEN-LAST:event_eventoMenuActionPerformed

    private void lembreteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lembreteMenuItemActionPerformed
        this.stickyFrame = new CadastroStickyNotesIFrame(this.stickyNotes, stickyNotesControl);
        desktopPane.add(this.stickyFrame);
    }//GEN-LAST:event_lembreteMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    private CalendarIFrame calframe;
    private CadastroDisciplina cadDisc;
    private CadastroEventoIFrame eventFrame;
    private CadastroDisciplina eventCadastroDisciplina;
    private CadastroStickyNotesIFrame stickyFrame;
    private List<StickyNotesIFrame> stickyNotes;

    private StickyNotesControl stickyNotesControl;
    private EventoControl eventoControl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu criarMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem disciplinaMenu;
    private javax.swing.JMenuItem eventoMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem lembreteMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem novoPeriodoMenuItem;
    private javax.swing.JMenu periodoMenu;
    // End of variables declaration//GEN-END:variables
}
